packages:
  - packages/*

allowBuilds:
  dprint: true
  esbuild: true

blockExoticSubdeps: true
minimumReleaseAge: 1440
verifyDepsBeforeRun: error

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    typescript: ^5.0.0 || ^6.0.0 || ^7.0.0
    vite: "*"
    vitest: "*"
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0-rc.1
  vitest: 5.0.1
  vite-plus: 1.0.0-rc.1
overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"
minimumReleaseAgeExclude:
  - vite-plus
  - "@voidzero-dev/*"
  - oxlint
  - "@oxlint/*"
  - oxlint-tsgolint
  - "@oxlint-tsgolint/*"
  - oxfmt
  - "@oxfmt/*"
  - vitest
  - "@vitest/*"
